//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.29 at 04:21:13 PM ICT 
//


package com.yipt.outbound.webservice;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sessionToken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="parentValuesListItemId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="valuesListItemName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="valuesListItemNumericValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sessionToken",
    "parentValuesListItemId",
    "valuesListItemName",
    "valuesListItemNumericValue"
})
@XmlRootElement(name = "CreateChildValuesListItemWithNumericValue")
public class CreateChildValuesListItemWithNumericValue {

    protected String sessionToken;
    protected int parentValuesListItemId;
    protected String valuesListItemName;
    @XmlElement(required = true)
    protected BigDecimal valuesListItemNumericValue;

    /**
     * Gets the value of the sessionToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionToken() {
        return sessionToken;
    }

    /**
     * Sets the value of the sessionToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionToken(String value) {
        this.sessionToken = value;
    }

    /**
     * Gets the value of the parentValuesListItemId property.
     * 
     */
    public int getParentValuesListItemId() {
        return parentValuesListItemId;
    }

    /**
     * Sets the value of the parentValuesListItemId property.
     * 
     */
    public void setParentValuesListItemId(int value) {
        this.parentValuesListItemId = value;
    }

    /**
     * Gets the value of the valuesListItemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuesListItemName() {
        return valuesListItemName;
    }

    /**
     * Sets the value of the valuesListItemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuesListItemName(String value) {
        this.valuesListItemName = value;
    }

    /**
     * Gets the value of the valuesListItemNumericValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValuesListItemNumericValue() {
        return valuesListItemNumericValue;
    }

    /**
     * Sets the value of the valuesListItemNumericValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValuesListItemNumericValue(BigDecimal value) {
        this.valuesListItemNumericValue = value;
    }

}
