//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.29 at 04:21:13 PM ICT 
//


package com.yipt.outbound.webservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DeleteValuesListValueResult" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deleteValuesListValueResult"
})
@XmlRootElement(name = "DeleteValuesListValueResponse")
public class DeleteValuesListValueResponse {

    @XmlElement(name = "DeleteValuesListValueResult")
    protected int deleteValuesListValueResult;

    /**
     * Gets the value of the deleteValuesListValueResult property.
     * 
     */
    public int getDeleteValuesListValueResult() {
        return deleteValuesListValueResult;
    }

    /**
     * Sets the value of the deleteValuesListValueResult property.
     * 
     */
    public void setDeleteValuesListValueResult(int value) {
        this.deleteValuesListValueResult = value;
    }

}
