//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.29 at 01:53:07 PM ICT 
//


package com.yipt.outbound.webservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.yipt.outbound.webservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.yipt.outbound.webservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateValuesListItemWithNumericValue }
     * 
     */
    public CreateValuesListItemWithNumericValue createCreateValuesListItemWithNumericValue() {
        return new CreateValuesListItemWithNumericValue();
    }

    /**
     * Create an instance of {@link CreateValuesListItemWithNumericValueResponse }
     * 
     */
    public CreateValuesListItemWithNumericValueResponse createCreateValuesListItemWithNumericValueResponse() {
        return new CreateValuesListItemWithNumericValueResponse();
    }

    /**
     * Create an instance of {@link CreateValuesListValue }
     * 
     */
    public CreateValuesListValue createCreateValuesListValue() {
        return new CreateValuesListValue();
    }

    /**
     * Create an instance of {@link CreateValuesListValueResponse }
     * 
     */
    public CreateValuesListValueResponse createCreateValuesListValueResponse() {
        return new CreateValuesListValueResponse();
    }

    /**
     * Create an instance of {@link CreateChildValuesListItemWithNumericValue }
     * 
     */
    public CreateChildValuesListItemWithNumericValue createCreateChildValuesListItemWithNumericValue() {
        return new CreateChildValuesListItemWithNumericValue();
    }

    /**
     * Create an instance of {@link CreateChildValuesListItemWithNumericValueResponse }
     * 
     */
    public CreateChildValuesListItemWithNumericValueResponse createCreateChildValuesListItemWithNumericValueResponse() {
        return new CreateChildValuesListItemWithNumericValueResponse();
    }

    /**
     * Create an instance of {@link CreateValuesListValueChild }
     * 
     */
    public CreateValuesListValueChild createCreateValuesListValueChild() {
        return new CreateValuesListValueChild();
    }

    /**
     * Create an instance of {@link CreateValuesListValueChildResponse }
     * 
     */
    public CreateValuesListValueChildResponse createCreateValuesListValueChildResponse() {
        return new CreateValuesListValueChildResponse();
    }

    /**
     * Create an instance of {@link UpdateValuesListItemWithNumericValue }
     * 
     */
    public UpdateValuesListItemWithNumericValue createUpdateValuesListItemWithNumericValue() {
        return new UpdateValuesListItemWithNumericValue();
    }

    /**
     * Create an instance of {@link UpdateValuesListItemWithNumericValueResponse }
     * 
     */
    public UpdateValuesListItemWithNumericValueResponse createUpdateValuesListItemWithNumericValueResponse() {
        return new UpdateValuesListItemWithNumericValueResponse();
    }

    /**
     * Create an instance of {@link UpdateValuesListNumericValueToNull }
     * 
     */
    public UpdateValuesListNumericValueToNull createUpdateValuesListNumericValueToNull() {
        return new UpdateValuesListNumericValueToNull();
    }

    /**
     * Create an instance of {@link UpdateValuesListNumericValueToNullResponse }
     * 
     */
    public UpdateValuesListNumericValueToNullResponse createUpdateValuesListNumericValueToNullResponse() {
        return new UpdateValuesListNumericValueToNullResponse();
    }

    /**
     * Create an instance of {@link UpdateValuesListValue }
     * 
     */
    public UpdateValuesListValue createUpdateValuesListValue() {
        return new UpdateValuesListValue();
    }

    /**
     * Create an instance of {@link UpdateValuesListValueResponse }
     * 
     */
    public UpdateValuesListValueResponse createUpdateValuesListValueResponse() {
        return new UpdateValuesListValueResponse();
    }

    /**
     * Create an instance of {@link LookupListValue }
     * 
     */
    public LookupListValue createLookupListValue() {
        return new LookupListValue();
    }

    /**
     * Create an instance of {@link LookupListValueResponse }
     * 
     */
    public LookupListValueResponse createLookupListValueResponse() {
        return new LookupListValueResponse();
    }

    /**
     * Create an instance of {@link DeleteValuesListValue }
     * 
     */
    public DeleteValuesListValue createDeleteValuesListValue() {
        return new DeleteValuesListValue();
    }

    /**
     * Create an instance of {@link DeleteValuesListValueResponse }
     * 
     */
    public DeleteValuesListValueResponse createDeleteValuesListValueResponse() {
        return new DeleteValuesListValueResponse();
    }

    /**
     * Create an instance of {@link GetValuesListValue }
     * 
     */
    public GetValuesListValue createGetValuesListValue() {
        return new GetValuesListValue();
    }

    /**
     * Create an instance of {@link GetValuesListValueResponse }
     * 
     */
    public GetValuesListValueResponse createGetValuesListValueResponse() {
        return new GetValuesListValueResponse();
    }

    /**
     * Create an instance of {@link GetValuesListValueWithTranslations }
     * 
     */
    public GetValuesListValueWithTranslations createGetValuesListValueWithTranslations() {
        return new GetValuesListValueWithTranslations();
    }

    /**
     * Create an instance of {@link GetValuesListValueWithTranslationsResponse }
     * 
     */
    public GetValuesListValueWithTranslationsResponse createGetValuesListValueWithTranslationsResponse() {
        return new GetValuesListValueWithTranslationsResponse();
    }

    /**
     * Create an instance of {@link GetValuesListItem }
     * 
     */
    public GetValuesListItem createGetValuesListItem() {
        return new GetValuesListItem();
    }

    /**
     * Create an instance of {@link GetValuesListItemResponse }
     * 
     */
    public GetValuesListItemResponse createGetValuesListItemResponse() {
        return new GetValuesListItemResponse();
    }

    /**
     * Create an instance of {@link GetValuesListItemWithTranslations }
     * 
     */
    public GetValuesListItemWithTranslations createGetValuesListItemWithTranslations() {
        return new GetValuesListItemWithTranslations();
    }

    /**
     * Create an instance of {@link GetValuesListItemWithTranslationsResponse }
     * 
     */
    public GetValuesListItemWithTranslationsResponse createGetValuesListItemWithTranslationsResponse() {
        return new GetValuesListItemWithTranslationsResponse();
    }

    /**
     * Create an instance of {@link GetValueListForField }
     * 
     */
    public GetValueListForField createGetValueListForField() {
        return new GetValueListForField();
    }

    /**
     * Create an instance of {@link GetValueListForFieldResponse }
     * 
     */
    public GetValueListForFieldResponse createGetValueListForFieldResponse() {
        return new GetValueListForFieldResponse();
    }

    /**
     * Create an instance of {@link GetValueListForFieldWithTranslations }
     * 
     */
    public GetValueListForFieldWithTranslations createGetValueListForFieldWithTranslations() {
        return new GetValueListForFieldWithTranslations();
    }

    /**
     * Create an instance of {@link GetValueListForFieldWithTranslationsResponse }
     * 
     */
    public GetValueListForFieldWithTranslationsResponse createGetValueListForFieldWithTranslationsResponse() {
        return new GetValueListForFieldWithTranslationsResponse();
    }

    /**
     * Create an instance of {@link GetValueListByParent }
     * 
     */
    public GetValueListByParent createGetValueListByParent() {
        return new GetValueListByParent();
    }

    /**
     * Create an instance of {@link GetValueListByParentResponse }
     * 
     */
    public GetValueListByParentResponse createGetValueListByParentResponse() {
        return new GetValueListByParentResponse();
    }

    /**
     * Create an instance of {@link GetValuesList }
     * 
     */
    public GetValuesList createGetValuesList() {
        return new GetValuesList();
    }

    /**
     * Create an instance of {@link GetValuesListResponse }
     * 
     */
    public GetValuesListResponse createGetValuesListResponse() {
        return new GetValuesListResponse();
    }

    /**
     * Create an instance of {@link GetValuesListWithTranslations }
     * 
     */
    public GetValuesListWithTranslations createGetValuesListWithTranslations() {
        return new GetValuesListWithTranslations();
    }

    /**
     * Create an instance of {@link GetValuesListWithTranslationsResponse }
     * 
     */
    public GetValuesListWithTranslationsResponse createGetValuesListWithTranslationsResponse() {
        return new GetValuesListWithTranslationsResponse();
    }

    /**
     * Create an instance of {@link GetValuesListValueIdByGUID }
     * 
     */
    public GetValuesListValueIdByGUID createGetValuesListValueIdByGUID() {
        return new GetValuesListValueIdByGUID();
    }

    /**
     * Create an instance of {@link GetValuesListValueIdByGUIDResponse }
     * 
     */
    public GetValuesListValueIdByGUIDResponse createGetValuesListValueIdByGUIDResponse() {
        return new GetValuesListValueIdByGUIDResponse();
    }

    /**
     * Create an instance of {@link GetValuesListIdByGUID }
     * 
     */
    public GetValuesListIdByGUID createGetValuesListIdByGUID() {
        return new GetValuesListIdByGUID();
    }

    /**
     * Create an instance of {@link GetValuesListIdByGUIDResponse }
     * 
     */
    public GetValuesListIdByGUIDResponse createGetValuesListIdByGUIDResponse() {
        return new GetValuesListIdByGUIDResponse();
    }

    /**
     * Create an instance of {@link GetFieldIdsByGUID }
     * 
     */
    public GetFieldIdsByGUID createGetFieldIdsByGUID() {
        return new GetFieldIdsByGUID();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link GetFieldIdsByGUIDResponse }
     * 
     */
    public GetFieldIdsByGUIDResponse createGetFieldIdsByGUIDResponse() {
        return new GetFieldIdsByGUIDResponse();
    }

    /**
     * Create an instance of {@link ArrayOfWebServiceKeyValuePair }
     * 
     */
    public ArrayOfWebServiceKeyValuePair createArrayOfWebServiceKeyValuePair() {
        return new ArrayOfWebServiceKeyValuePair();
    }

    /**
     * Create an instance of {@link GetFieldIdByGUID }
     * 
     */
    public GetFieldIdByGUID createGetFieldIdByGUID() {
        return new GetFieldIdByGUID();
    }

    /**
     * Create an instance of {@link GetFieldIdByGUIDResponse }
     * 
     */
    public GetFieldIdByGUIDResponse createGetFieldIdByGUIDResponse() {
        return new GetFieldIdByGUIDResponse();
    }

    /**
     * Create an instance of {@link CreateUserSession }
     * 
     */
    public CreateUserSession createCreateUserSession() {
        return new CreateUserSession();
    }

    /**
     * Create an instance of {@link CreateUserSessionResponse }
     * 
     */
    public CreateUserSessionResponse createCreateUserSessionResponse() {
        return new CreateUserSessionResponse();
    }

    /**
     * Create an instance of {@link CreateDomainUserSession }
     * 
     */
    public CreateDomainUserSession createCreateDomainUserSession() {
        return new CreateDomainUserSession();
    }

    /**
     * Create an instance of {@link CreateDomainUserSessionResponse }
     * 
     */
    public CreateDomainUserSessionResponse createCreateDomainUserSessionResponse() {
        return new CreateDomainUserSessionResponse();
    }

    /**
     * Create an instance of {@link CreateUserSessionFromInstance }
     * 
     */
    public CreateUserSessionFromInstance createCreateUserSessionFromInstance() {
        return new CreateUserSessionFromInstance();
    }

    /**
     * Create an instance of {@link CreateUserSessionFromInstanceResponse }
     * 
     */
    public CreateUserSessionFromInstanceResponse createCreateUserSessionFromInstanceResponse() {
        return new CreateUserSessionFromInstanceResponse();
    }

    /**
     * Create an instance of {@link CreateDomainUserSessionFromInstance }
     * 
     */
    public CreateDomainUserSessionFromInstance createCreateDomainUserSessionFromInstance() {
        return new CreateDomainUserSessionFromInstance();
    }

    /**
     * Create an instance of {@link CreateDomainUserSessionFromInstanceResponse }
     * 
     */
    public CreateDomainUserSessionFromInstanceResponse createCreateDomainUserSessionFromInstanceResponse() {
        return new CreateDomainUserSessionFromInstanceResponse();
    }

    /**
     * Create an instance of {@link TerminateSession }
     * 
     */
    public TerminateSession createTerminateSession() {
        return new TerminateSession();
    }

    /**
     * Create an instance of {@link TerminateSessionResponse }
     * 
     */
    public TerminateSessionResponse createTerminateSessionResponse() {
        return new TerminateSessionResponse();
    }

    /**
     * Create an instance of {@link GetSearchOptions }
     * 
     */
    public GetSearchOptions createGetSearchOptions() {
        return new GetSearchOptions();
    }

    /**
     * Create an instance of {@link GetSearchOptionsResponse }
     * 
     */
    public GetSearchOptionsResponse createGetSearchOptionsResponse() {
        return new GetSearchOptionsResponse();
    }

    /**
     * Create an instance of {@link GetSearchOptionsByGuid }
     * 
     */
    public GetSearchOptionsByGuid createGetSearchOptionsByGuid() {
        return new GetSearchOptionsByGuid();
    }

    /**
     * Create an instance of {@link GetSearchOptionsByGuidResponse }
     * 
     */
    public GetSearchOptionsByGuidResponse createGetSearchOptionsByGuidResponse() {
        return new GetSearchOptionsByGuidResponse();
    }

    /**
     * Create an instance of {@link ExecuteSearch }
     * 
     */
    public ExecuteSearch createExecuteSearch() {
        return new ExecuteSearch();
    }

    /**
     * Create an instance of {@link ExecuteSearchResponse }
     * 
     */
    public ExecuteSearchResponse createExecuteSearchResponse() {
        return new ExecuteSearchResponse();
    }

    /**
     * Create an instance of {@link ExecuteStatisticSearch }
     * 
     */
    public ExecuteStatisticSearch createExecuteStatisticSearch() {
        return new ExecuteStatisticSearch();
    }

    /**
     * Create an instance of {@link ExecuteStatisticSearchResponse }
     * 
     */
    public ExecuteStatisticSearchResponse createExecuteStatisticSearchResponse() {
        return new ExecuteStatisticSearchResponse();
    }

    /**
     * Create an instance of {@link ExecuteStatisticSearchByReport }
     * 
     */
    public ExecuteStatisticSearchByReport createExecuteStatisticSearchByReport() {
        return new ExecuteStatisticSearchByReport();
    }

    /**
     * Create an instance of {@link ExecuteStatisticSearchByReportResponse }
     * 
     */
    public ExecuteStatisticSearchByReportResponse createExecuteStatisticSearchByReportResponse() {
        return new ExecuteStatisticSearchByReportResponse();
    }

    /**
     * Create an instance of {@link ExecuteQuickSearchWithSolutionId }
     * 
     */
    public ExecuteQuickSearchWithSolutionId createExecuteQuickSearchWithSolutionId() {
        return new ExecuteQuickSearchWithSolutionId();
    }

    /**
     * Create an instance of {@link ExecuteQuickSearchWithSolutionIdResponse }
     * 
     */
    public ExecuteQuickSearchWithSolutionIdResponse createExecuteQuickSearchWithSolutionIdResponse() {
        return new ExecuteQuickSearchWithSolutionIdResponse();
    }

    /**
     * Create an instance of {@link ExecuteQuickSearchWithModuleIds }
     * 
     */
    public ExecuteQuickSearchWithModuleIds createExecuteQuickSearchWithModuleIds() {
        return new ExecuteQuickSearchWithModuleIds();
    }

    /**
     * Create an instance of {@link ExecuteQuickSearchWithModuleIdsResponse }
     * 
     */
    public ExecuteQuickSearchWithModuleIdsResponse createExecuteQuickSearchWithModuleIdsResponse() {
        return new ExecuteQuickSearchWithModuleIdsResponse();
    }

    /**
     * Create an instance of {@link SearchRecords }
     * 
     */
    public SearchRecords createSearchRecords() {
        return new SearchRecords();
    }

    /**
     * Create an instance of {@link SearchRecordsResponse }
     * 
     */
    public SearchRecordsResponse createSearchRecordsResponse() {
        return new SearchRecordsResponse();
    }

    /**
     * Create an instance of {@link SearchRecordsByField }
     * 
     */
    public SearchRecordsByField createSearchRecordsByField() {
        return new SearchRecordsByField();
    }

    /**
     * Create an instance of {@link SearchRecordsByFieldResponse }
     * 
     */
    public SearchRecordsByFieldResponse createSearchRecordsByFieldResponse() {
        return new SearchRecordsByFieldResponse();
    }

    /**
     * Create an instance of {@link CheckSearchStatus }
     * 
     */
    public CheckSearchStatus createCheckSearchStatus() {
        return new CheckSearchStatus();
    }

    /**
     * Create an instance of {@link CheckSearchStatusResponse }
     * 
     */
    public CheckSearchStatusResponse createCheckSearchStatusResponse() {
        return new CheckSearchStatusResponse();
    }

    /**
     * Create an instance of {@link CheckSearchStatusByPageSize }
     * 
     */
    public CheckSearchStatusByPageSize createCheckSearchStatusByPageSize() {
        return new CheckSearchStatusByPageSize();
    }

    /**
     * Create an instance of {@link CheckSearchStatusByPageSizeResponse }
     * 
     */
    public CheckSearchStatusByPageSizeResponse createCheckSearchStatusByPageSizeResponse() {
        return new CheckSearchStatusByPageSizeResponse();
    }

    /**
     * Create an instance of {@link RetrieveSearchResultsPage }
     * 
     */
    public RetrieveSearchResultsPage createRetrieveSearchResultsPage() {
        return new RetrieveSearchResultsPage();
    }

    /**
     * Create an instance of {@link RetrieveSearchResultsPageResponse }
     * 
     */
    public RetrieveSearchResultsPageResponse createRetrieveSearchResultsPageResponse() {
        return new RetrieveSearchResultsPageResponse();
    }

    /**
     * Create an instance of {@link RetrieveSearchResultsPageByPageSize }
     * 
     */
    public RetrieveSearchResultsPageByPageSize createRetrieveSearchResultsPageByPageSize() {
        return new RetrieveSearchResultsPageByPageSize();
    }

    /**
     * Create an instance of {@link RetrieveSearchResultsPageByPageSizeResponse }
     * 
     */
    public RetrieveSearchResultsPageByPageSizeResponse createRetrieveSearchResultsPageByPageSizeResponse() {
        return new RetrieveSearchResultsPageByPageSizeResponse();
    }

    /**
     * Create an instance of {@link GetReports }
     * 
     */
    public GetReports createGetReports() {
        return new GetReports();
    }

    /**
     * Create an instance of {@link GetReportsResponse }
     * 
     */
    public GetReportsResponse createGetReportsResponse() {
        return new GetReportsResponse();
    }

    /**
     * Create an instance of {@link SearchRecordsByReport }
     * 
     */
    public SearchRecordsByReport createSearchRecordsByReport() {
        return new SearchRecordsByReport();
    }

    /**
     * Create an instance of {@link SearchRecordsByReportResponse }
     * 
     */
    public SearchRecordsByReportResponse createSearchRecordsByReportResponse() {
        return new SearchRecordsByReportResponse();
    }

    /**
     * Create an instance of {@link WebServiceKeyValuePair }
     * 
     */
    public WebServiceKeyValuePair createWebServiceKeyValuePair() {
        return new WebServiceKeyValuePair();
    }

}
